/**
 * 1.CHANGE_CATALOG_TYPE: 修改catalog的类型
 */
export const CHANGE_CATALOG_TYPE = 'CHANGE_CATALOG_TYPE'; 
export type CHANGE_CATALOG_TYPE = typeof CHANGE_CATALOG_TYPE;

/**
 * 2.Change_CATALOG_MODELS: 获取catalog模型数据
 */
export const CHANGE_CATALOG_MODELS = 'CHANGE_CATALOG_MODELS';
export type CHANGE_CATALOG_MODELS = typeof CHANGE_CATALOG_MODELS;

/**
 * 3.RESET_CATALOG_PAGEINDEX: 重置catalog分页
 */
export const RESET_CATALOG_PAGEINDEX = 'RESET_CATALOG_PAGEINDEX';
export type RESET_CATALOG_PAGEINDEX = typeof RESET_CATALOG_PAGEINDEX;

/**
 * 4.RECORD_SELECTED_CATEGORY_ID: 记录被选中的category id
 */
export const RECORD_SELECTED_CATEGORY_ID = 'RECORD_SELECTED_CATEGORY_ID';
export type RECORD_SELECTED_CATEGORY_ID = typeof RECORD_SELECTED_CATEGORY_ID;